// Deterministic integration checks. Only the WebGL renderer and browser shell are mocked.
import fs from 'node:fs';
import assert from 'node:assert/strict';
import * as real from '../vendor/three.module.js';
import {createEzreal} from '../src/characters/ezreal.js';
import {SPELLS,SpellSystem} from '../src/combat/spells.js';
import {SpellEffects} from '../src/combat/spell-effects.js';
import {AttackSystem,BASIC_ATTACK,isAlive} from '../src/combat/attacks.js';
import {EnemySystem as RealEnemySystem} from '../src/enemies/enemies.js';
import {HoldCamera,smoothAngle} from '../src/motion.js';
class EnemySystem extends RealEnemySystem {constructor(scene,hero){super(scene,hero,{random:()=>0.5});}}
const root=new URL('../',import.meta.url);
const character=createEzreal();
assert.equal(character.root.name,'Ezreal');
assert.equal(character.arms.length,2);assert.equal(character.legs.length,2);
assert.equal(character.muzzle.parent,character.gauntlet);
character.animate({time:1,phase:1,weight:1,dt:1/60});
assert.notEqual(character.legs[0].hip.rotation.x,0);
assert.notEqual(character.arms[0].shoulder.rotation.x,0);
character.animate({time:2,phase:1,weight:0,dt:1/60});
assert.equal(Math.abs(character.legs[0].hip.rotation.x),0);
character.root.updateMatrixWorld(true);
character.root.traverse(o=>assert(o.matrixWorld.elements.every(Number.isFinite)));
let now=0;
class Clock{getDelta(){now+=1/60;return 1/60}get elapsedTime(){return now}}
let renderedScene,renderedCamera;
class Renderer{constructor(){this.shadowMap={}}setPixelRatio(){}setSize(){}render(scene,camera){renderedScene=scene;renderedCamera=camera;scene.updateMatrixWorld(true)}}
const THREE={...real,WebGLRenderer:Renderer,Clock};
const elements={};
for(const id of ['#world','#reset','#loading','#error','#enemy-stats','#spell-message',...['Q','W','E','R'].flatMap(k=>['#spell-'+k,'#cooldown-'+k])])elements[id]={style:{},hidden:false,textContent:'',listeners:{},setAttribute(){},addEventListener(k,fn){this.listeners[k]=fn},focus(){},getBoundingClientRect(){return{left:0,top:0,width:1280,height:800}}};
const docEvents={};globalThis.document={querySelector:id=>elements[id],hidden:false,addEventListener(k,fn){docEvents[k]=fn}};
const keys={};globalThis.window={addEventListener(k,fn){keys[k]=fn}};
globalThis.innerWidth=1280;globalThis.innerHeight=800;globalThis.devicePixelRatio=1;
let frame;globalThis.requestAnimationFrame=fn=>{frame=fn};
let game=fs.readFileSync(new URL('src/game.js',root),'utf8').replace(/^import .*;\n/gm,'');
new Function('THREE','createEzreal','SPELLS','SpellSystem','SpellEffects','AttackSystem','BASIC_ATTACK','isAlive','EnemySystem','HoldCamera','smoothAngle',game)(THREE,createEzreal,SPELLS,SpellSystem,SpellEffects,AttackSystem,BASIC_ATTACK,isAlive,EnemySystem,HoldCamera,smoothAngle);
const tick=(n=1)=>{for(let i=0;i<n;i++)frame()};
const click=(button,x,y,shiftKey=false)=>elements['#world'].listeners.pointerdown({button,clientX:x,clientY:y,shiftKey,preventDefault(){}});
const key=code=>keys.keydown({code,preventDefault(){}});
const heroRoot=renderedScene.children.find(object=>object.name==='Ezreal');
assert(heroRoot);
const initial=heroRoot.position.clone();
assert.equal(elements['#loading'].hidden,true);
click(0,750,400);tick();assert(heroRoot.position.distanceTo(initial)>0.01);
tick(240);assert(heroRoot.position.distanceTo(initial)>0.1);
const arrived=heroRoot.position.clone();tick(60);assert(heroRoot.position.distanceTo(arrived)<1e-10);
click(2,100,150);tick(3);key('KeyS');tick();
const stopped=heroRoot.position.clone();tick(60);assert(heroRoot.position.distanceTo(stopped)<1e-10);
click(2,100,150);tick(600);
assert(Math.abs(heroRoot.position.x)<=18.5&&Math.abs(heroRoot.position.z)<=18.5);
elements['#reset'].listeners.click();tick();assert(heroRoot.position.distanceTo(initial)<1e-10);
// A moving right-click destination survives the short spell lock and resumes afterward.
click(2,850,400);tick(18);const beforeCast=heroRoot.position.clone();
key('KeyQ');tick(3);assert(heroRoot.position.distanceTo(beforeCast)<1e-10);
tick(30);const afterCast=heroRoot.position.clone();tick(60);assert(heroRoot.position.distanceTo(afterCast)>0.1);
elements['#reset'].listeners.click();tick();
key('KeyQ');tick(15);assert.match(elements['#cooldown-Q'].textContent,/초/);
key('KeyW');tick(15);assert.match(elements['#cooldown-W'].textContent,/초/);
key('KeyE');tick(30);assert(heroRoot.position.distanceTo(initial)>0.1);
key('KeyR');tick(20);assert.equal(elements['#spell-R'].disabled,true);
tick(160);
elements['#reset'].listeners.click();tick();assert.equal(elements['#cooldown-Q'].textContent,'준비');
assert(heroRoot.position.distanceTo(initial)<1e-10);
// Hold Space through movement, then release and confirm camera stays put.
key('Space');tick(60);
const cameraBefore=renderedCamera.position.clone();
click(0,850,400);tick(90);assert(renderedCamera.position.distanceTo(cameraBefore)>0.1);
keys.keyup({code:'Space',preventDefault(){}});
const frozenCamera=renderedCamera.position.clone();click(0,400,400);tick(60);
assert(renderedCamera.position.distanceTo(frozenCamera)<1e-10);
key('Space');keys.blur();const blurCamera=renderedCamera.position.clone();tick(30);assert(renderedCamera.position.distanceTo(blurCamera)<1e-10);
// Real projection and raycasting: right-click the rendered enemy body.
elements['#reset'].listeners.click();tick();
const enemyRoot=renderedScene.children.find(o=>o.userData.enemy&&o.userData.enemy.position.z===18.2);
const visibleEnemy=enemyRoot||renderedScene.children.find(o=>o.userData.enemy);
const projected=visibleEnemy.position.clone().add(new real.Vector3(0,1,0)).project(renderedCamera);
click(2,(projected.x*.5+.5)*1280,(-projected.y*.5+.5)*800);tick(90);
assert(visibleEnemy.userData.enemy.health<200);
key('KeyS');const attackStopped=heroRoot.position.clone();tick(60);assert(heroRoot.position.distanceTo(attackStopped)<1e-10);
console.log('PASS: model joints and animation, finite transforms, movement, arrival, right-click, stop, bounds, reset. WebGL rendering excluded.');
